/**
 * Generated by FakerAndroid for doc or help by https://github.com/Efaker/FakerAndroid
 */
package com.anygames.sdk;

import android.util.Log;

public final class Logger {
    private static final boolean DEBUG = false;

//    private static final boolean DEBUG = true;
    private static final String TAG = "anygames";
    public static void log(String log){
        if(DEBUG){
            Log.e(TAG,log);
        }
    }
}
